enum session_states {
	SESSION_ST_NONE = 0,		//  0
	SESSION_ST_SENT_CMD,		//  1
	SESSION_ST_CONNECTING,		//  2
	SESSION_ST_CONNECTED,		//  3
	SESSION_ST_AWAIT_220,		//  4

	SESSION_ST_TLS_START,		//  5
	SESSION_ST_TLS_PHASE_TLS,	//  6
	SESSION_ST_TLS_PHASE_SSL,	//  7
	SESSION_ST_TLS_INIT,		//  8
	SESSION_ST_TLS_WAIT,		//  9
	
	SESSION_ST_LOGIN_START,		// 10
	SESSION_ST_LOGIN_SENT_USER,	// 11
	SESSION_ST_LOGIN_SENT_PASS,	// 12

	SESSION_ST_REPLY_PBSZ,		// 13

	SESSION_ST_MISC,		// 14
	SESSION_ST_MISC_REPLY_SYST,	// 15
	SESSION_ST_MISC_REPLY_CLNT,	// 16
	SESSION_ST_MISC_REPLY_FEAT,	// 17

	SESSION_ST_MISC_REPLY_XDUPE,	// 18

	SESSION_ST_TYPE_REPLY,		// 19
	SESSION_ST_PROT_REPLY,		// 20
	SESSION_ST_PRET_REPLY,		// 21
	SESSION_ST_PASV_REPLY,		// 22
	SESSION_ST_PORT_REPLY,		// 23

	SESSION_ST_DATA_TRANSFER,	// 24
	SESSION_ST_DATA_FINISH,		// 25


	SESSION_ST_IDLE,		// 26

	SESSION_ST_RELAY_TYPE_ASCII,	// 27
	SESSION_ST_RELAY_TYPE_BINARY,	// 28

	SESSION_ST_RELAY_CCSN_OFF,	// 29
	SESSION_ST_RELAY_CCSN_ON,	// 30

	SESSION_ST_RELAY_SSCN_OFF,	// 31
	SESSION_ST_RELAY_SSCN_ON,	// 32

	SESSION_ST_RELAY_PRIVACY_OFF,	// 33
	SESSION_ST_RELAY_PRIVACY_ON,	// 34

	SESSION_ST_RELAY_CWD,		// 35
	SESSION_ST_RELAY_SIZE,		// 36
	SESSION_ST_RELAY_REST_ON,	// 37
	SESSION_ST_RELAY_REST_OFF,	// 38

	SESSION_ST_RELAY_STOR,		// 39
	SESSION_ST_RELAY_RETR,		// 40
	SESSION_ST_RELAY_226,		// 41

	SESSION_ST_PWD_INTERNAL,	// 42

	SESSION_ST_STAT_REPLY,		// 43

	SESSION_ST_TEST				// 44
};

typedef enum session_states session_state_t;
